import type { Thread, User, Comment } from './types'
import { generateAvatarColor } from './utils'

export const SEED_USERS: User[] = [
  {
    id: 'user-admin',
    username: 'admin_lapau',
    role: 'admin',
    level: 'pangulu-lapau',
    totalPosts: 156,
    totalReactions: 892,
    createdAt: Date.now() - 365 * 24 * 60 * 60 * 1000,
    avatarColor: generateAvatarColor('user-admin'),
  },
  {
    id: 'user-1',
    username: 'urang_awak_01',
    role: 'user',
    level: 'urang-lamo',
    totalPosts: 45,
    totalReactions: 234,
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
    avatarColor: generateAvatarColor('user-1'),
  },
  {
    id: 'user-2',
    username: 'perantau_jakarta',
    role: 'user',
    level: 'tukang-kieeh',
    totalPosts: 28,
    totalReactions: 156,
    createdAt: Date.now() - 120 * 24 * 60 * 60 * 1000,
    avatarColor: generateAvatarColor('user-2'),
  },
  {
    id: 'user-3',
    username: 'anak_rantau',
    role: 'user',
    level: 'urang-awak',
    totalPosts: 12,
    totalReactions: 67,
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    avatarColor: generateAvatarColor('user-3'),
  },
  {
    id: 'user-4',
    username: 'lapau_kopi',
    role: 'user',
    level: 'niniak-mamak',
    totalPosts: 89,
    totalReactions: 445,
    createdAt: Date.now() - 200 * 24 * 60 * 60 * 1000,
    avatarColor: generateAvatarColor('user-4'),
  },
]

export const SEED_THREADS: Thread[] = [
  {
    id: 'thread-1',
    authorId: 'user-1',
    authorUsername: 'urang_awak_01',
    title: 'Rendang Terenak di Padang, Wajib Dicoba!',
    content: 'Baru pulang kampuang, nyobain rendang di Rumah Makan Lamun Ombak. Bener-bener enak! Dagingnya empuk, bumbu meresap sampai ke dalam. Ini foto-fotonya, dijamin ngiler!',
    category: 'lapau-umum',
    status: 'approved',
    createdAt: Date.now() - 2 * 60 * 60 * 1000,
    reactions: {
      'rendang': ['user-2', 'user-3', 'user-4'],
      'teh-talua': ['user-4'],
      'langkitang': [],
      'soto-padang': ['user-2'],
      'samba-lado': [],
      'gulai': [],
      'asin': [],
    },
    commentCount: 12,
    media: [
      {
        id: 'media-1',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&h=600&fit=crop',
      },
      {
        id: 'media-2',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1625398407796-82650a8c135f?w=800&h=600&fit=crop',
      },
    ],
  },
  {
    id: 'thread-2',
    authorId: 'user-2',
    authorUsername: 'perantau_jakarta',
    title: 'Kangen Kampuang, Siapa yang Sama?',
    content: 'Udah 3 tahun di rantau, kangen banget sama suasana kampung. Rindu jalan-jalan sore ke sawah, minum kopi di lapau, ngobrol sama urang kampuang. Share dong cerita kalian di rantau!',
    category: 'curhat-lapau',
    status: 'approved',
    createdAt: Date.now() - 5 * 60 * 60 * 1000,
    reactions: {
      'rendang': ['user-1'],
      'teh-talua': ['user-1', 'user-3', 'user-4'],
      'langkitang': [],
      'soto-padang': [],
      'samba-lado': [],
      'gulai': ['user-3'],
      'asin': [],
    },
    commentCount: 28,
    media: [
      {
        id: 'media-3',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1474418397713-7ede21d49118?w=800&h=600&fit=crop',
      },
    ],
  },
  {
    id: 'thread-3',
    authorId: 'user-4',
    authorUsername: 'lapau_kopi',
    title: 'Warung Kopi di Bukittinggi yang Instagramable',
    content: 'Rekomendasi warung kopi dengan view bagus di Bukittinggi nih. Pas banget buat ngopi sambil menikmati pemandangan. Harganya juga ramah di kantong!',
    category: 'lapau-umum',
    status: 'approved',
    createdAt: Date.now() - 8 * 60 * 60 * 1000,
    reactions: {
      'rendang': ['user-1', 'user-2'],
      'teh-talua': ['user-3'],
      'langkitang': [],
      'soto-padang': [],
      'samba-lado': [],
      'gulai': [],
      'asin': [],
    },
    commentCount: 15,
    media: [
      {
        id: 'media-4',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&h=600&fit=crop',
      },
      {
        id: 'media-5',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop',
      },
      {
        id: 'media-6',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&h=600&fit=crop',
      },
    ],
  },
  {
    id: 'thread-4',
    authorId: 'user-3',
    authorUsername: 'anak_rantau',
    title: 'Tips Usaha UMKM Rendang Ala Rumahan',
    content: 'Buat yang mau mulai usaha rendang, aku share tips dari pengalaman jualan rendang rumahan. Alhamdulillah sekarang udah punya pelanggan tetap. Kuncinya di bumbu dan kesabaran memasak!',
    category: 'umkm-bisnis',
    status: 'approved',
    createdAt: Date.now() - 12 * 60 * 60 * 1000,
    reactions: {
      'rendang': ['user-1', 'user-2', 'user-4'],
      'teh-talua': ['user-1', 'user-4'],
      'langkitang': [],
      'soto-padang': ['user-2', 'user-4'],
      'samba-lado': [],
      'gulai': [],
      'asin': [],
    },
    commentCount: 34,
  },
  {
    id: 'thread-5',
    authorId: 'user-1',
    authorUsername: 'urang_awak_01',
    title: 'Cerita Lucu di Lapau Semalam, Bikin Ngakak!',
    content: 'Semalam duduk di lapau, ada kejadian lucu banget. Ada bapak-bapak beli kopi, eh salah duduk di meja orang. Sambil nyeruput kopi orang lain pula! Pas ketahuan, mukanya merah padam 😂',
    category: 'sindie-sarkas',
    status: 'approved',
    createdAt: Date.now() - 15 * 60 * 60 * 1000,
    reactions: {
      'rendang': [],
      'teh-talua': [],
      'langkitang': ['user-2', 'user-3', 'user-4'],
      'soto-padang': [],
      'samba-lado': [],
      'gulai': [],
      'asin': [],
    },
    commentCount: 8,
  },
  {
    id: 'thread-6',
    authorId: 'user-2',
    authorUsername: 'perantau_jakarta',
    title: 'Foto-foto Jam Gadang dari Berbagai Angle',
    content: 'Collection foto Jam Gadang yang aku ambil beberapa bulan lalu. Landmark paling ikonik di Bukittinggi! Kalau kalian punya foto Jam Gadang, share juga dong!',
    category: 'lapau-umum',
    status: 'approved',
    createdAt: Date.now() - 20 * 60 * 60 * 1000,
    reactions: {
      'rendang': ['user-1', 'user-3'],
      'teh-talua': ['user-4'],
      'langkitang': [],
      'soto-padang': [],
      'samba-lado': [],
      'gulai': [],
      'asin': [],
    },
    commentCount: 6,
    media: [
      {
        id: 'media-7',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1555881400-69d011c91b0e?w=800&h=600&fit=crop',
      },
    ],
  },
  {
    id: 'thread-7',
    authorId: 'user-4',
    authorUsername: 'lapau_kopi',
    title: 'Pemandangan Danau Maninjau yang Bikin Adem',
    content: 'Weekend kemarin ke Danau Maninjau, subhanallah indahnya! Udara sejuk, pemandangan indah. Cocok banget buat healing dari penat kerjaan. Ini beberapa foto yang sempat aku ambil.',
    category: 'lapau-umum',
    status: 'approved',
    createdAt: Date.now() - 24 * 60 * 60 * 1000,
    reactions: {
      'rendang': ['user-1', 'user-2', 'user-3'],
      'teh-talua': ['user-1'],
      'langkitang': [],
      'soto-padang': [],
      'samba-lado': [],
      'gulai': ['user-2'],
      'asin': [],
    },
    commentCount: 11,
    media: [
      {
        id: 'media-8',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
      },
      {
        id: 'media-9',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&h=600&fit=crop',
      },
    ],
  },
  {
    id: 'thread-8',
    authorId: 'user-3',
    authorUsername: 'anak_rantau',
    title: 'Diskusi: Kebijakan Pariwisata Sumatera Barat',
    content: 'Menurut kalian, gimana kebijakan pariwisata di Sumbar sekarang? Apakah sudah cukup mendukung UMKM lokal? Yuk diskusi santai tapi serius!',
    category: 'politik-lapau',
    status: 'approved',
    createdAt: Date.now() - 30 * 60 * 60 * 1000,
    reactions: {
      'rendang': [],
      'teh-talua': ['user-1'],
      'langkitang': [],
      'soto-padang': ['user-2', 'user-4'],
      'samba-lado': ['user-1'],
      'gulai': [],
      'asin': [],
    },
    commentCount: 42,
  },
  {
    id: 'thread-9',
    authorId: 'user-1',
    authorUsername: 'urang_awak_01',
    title: 'Tutorial Masak Gulai Ikan Mas, Gampang Banget!',
    content: 'Bagi resep gulai ikan mas ala rumahan. Sederhana tapi rasanya mantap! Langkah-langkahnya mudah, cocok buat pemula. Foto hasil masakannya ada di bawah ya!',
    category: 'lapau-umum',
    status: 'approved',
    createdAt: Date.now() - 36 * 60 * 60 * 1000,
    reactions: {
      'rendang': ['user-2', 'user-3'],
      'teh-talua': ['user-4'],
      'langkitang': [],
      'soto-padang': [],
      'samba-lado': [],
      'gulai': ['user-2', 'user-4'],
      'asin': [],
    },
    commentCount: 19,
    media: [
      {
        id: 'media-10',
        type: 'image',
        url: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&h=600&fit=crop',
      },
    ],
  },
  {
    id: 'thread-10',
    authorId: 'user-2',
    authorUsername: 'perantau_jakarta',
    title: 'Anak Rantau, Kapan Terakhir Pulang Kampung?',
    content: 'Serius nanya nih, kapan terakhir kalian pulang kampung? Aku udah lama banget ga pulang, kangennya udah ga tahan. Cerita dong pengalaman terakhir pulang kampung!',
    category: 'curhat-lapau',
    status: 'approved',
    createdAt: Date.now() - 48 * 60 * 60 * 1000,
    reactions: {
      'rendang': [],
      'teh-talua': ['user-1', 'user-3'],
      'langkitang': [],
      'soto-padang': [],
      'samba-lado': [],
      'gulai': ['user-4'],
      'asin': ['user-3'],
    },
    commentCount: 52,
  },
]

export const SEED_COMMENTS: Comment[] = [
  {
    id: 'comment-1',
    threadId: 'thread-1',
    authorId: 'user-2',
    authorUsername: 'perantau_jakarta',
    content: 'Wah mantap! Aku juga pernah makan di sini, emang juara rendangnya!',
    createdAt: Date.now() - 1.5 * 60 * 60 * 1000,
  },
  {
    id: 'comment-2',
    threadId: 'thread-1',
    authorId: 'user-3',
    authorUsername: 'anak_rantau',
    content: 'Ngiler lihat fotonya! Kapan ya bisa ke Padang lagi...',
    createdAt: Date.now() - 1 * 60 * 60 * 1000,
  },
]

export function initializeSeedData(
  users: User[],
  threads: Thread[],
  comments: Comment[]
): { users: User[]; threads: Thread[]; comments: Comment[] } {
  if (users.length === 0 && threads.length === 0) {
    return {
      users: SEED_USERS,
      threads: SEED_THREADS,
      comments: SEED_COMMENTS,
    }
  }
  
  return { users, threads, comments }
}
